### PR TITLE
Added Spanish translations

### PR DESCRIPTION
**Pull request by voghDev**
As I promised in #164, I've added spanish translations for Done and Skip buttons.

### CODE REVIEW

**Comment by avluis** [comment]
Looks good~

**Comment by Andrew-Quebe** [comment]
@voghDev refer to issue #5 again if you want to help translate the example app strings.

**Comment by voghDev** [comment]
Ok, I'll have a look and translate the samples aswell

**Comment by Andrew-Quebe** [comment]
Just keep in mind that the sample app isn't done.

**Pull request merged**
