### PR TITLE
onDotSelected

### PR DESCRIPTION
**Pull request by Fleker**
I'm using this in one of my apps and thought it would be a good way to do permission requests in the M permissions model. ie. Slide A talks about using location. As you go to Slide B, it requests location.

This isn't possible in the current library without some hacking, so I added this new method that can be overriden.

### CODE REVIEW

**Comment by PaoloRotolo** [comment]
LGTM, thanks!

**Comment by PaoloRotolo** [comment]
Actually, I can't automatically merge your pull. Can you please update it?

Thanks!

**Comment by Fleker** [comment]
Ok, my fork is now up-to-date with yours. The pull request should work now.

**Comment by PaoloRotolo** [comment]
Merged, thanks again!

**Pull request merged**
