### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by Andrew-Quebe**
Added my app to the list of apps using this library.

### CODE REVIEW

**Comment by PaoloRotolo** [comment]
Hi Andrew,
I've seen your mail too. I really like your app, you did a great job integrating planets with material elements of UI :)

Can you please upload the new apk on Google Play first? Users want to see real life examples of how developers are using this library to get inspired.

Ping me when the new version is available to all :+1:

**Comment by Andrew-Quebe** [comment]
Will do! Should be out in the next couple days hopefully.

**Comment by Andrew-Quebe** [comment]
@PaoloRotolo I'm going to close this PR and make a new one when I release the app. There seems to be some merge conflicts.

**Comment by PaoloRotolo** [comment]
Sure, thanks :)

**Pull request closed without merging**
