### PR TITLE
API-9 compatibility

### PR DESCRIPTION
**Pull request by marbat87**
Added usage of nineoldandroids in order to extend compatibility to
pre-Honeycomb

### CODE REVIEW

**Comment by PaoloRotolo** [comment]
LGTM. Thank you!

**Comment by marbat87** [comment]
I forgot the ViewHelper import in FadePageTransformer.java. I don't know if it's added automatically.

**Comment by PaoloRotolo** [comment]
Yep, my Android Studio added it automatically.
Anyway, I've this when I try to compile: 
```
Error:(38, 29) No resource found that matches the given name (at 'style' with value '?attr/borderlessButtonStyle').
```

Does it work for you locally?

**Comment by marbat87** [comment]
Ooops I forgot AppCompat dependecy. Try to merge the new pull request. Everything should work now :)
https://github.com/PaoloRotolo/AppIntro/pull/51

**Pull request merged**
