### PR TITLE
Addressing issue #318

### PR DESCRIPTION
**Pull request by ameykshirsagar**
This pull request is addressing following issue
The custom typeface is not being set when we use 
````
addSlide(AppIntroFragment.newInstance("Setup Panel","OpenSans-Light.ttf", "Lets go through the setup step by step","OpenSans-Regular.ttf" ,R.mipmap.ic_launcher, Color.parseColor("#3F51B5")));
````
Cause:-
AppIntroBaseFragment.java:89
````
....
if (titleTypeface != null && titleTypeface.equals("")) {
....
````
& 
AppIntroBaseFragment.java:98
````
....
if (descTypeface != null && descTypeface.equals("")) {
....
````
`titleTypeface.equals("")` & `descTypeface.equals("")` causes the condition to get false if we pass a non-empty valid string as a path. The empty string check is transferred to `CustomFontCache` class with appropriate log message.

If there are any issues let me know. The code is pull request is tested already

Thanks

### CODE REVIEW

**Comment by ameykshirsagar** [comment]
Also I have updated the build tools version to 24.0.3

**Comment by avluis** [comment]
Can you work off the latest master?

**Comment by ameykshirsagar** [comment]
I actually found the issue in the latest master as well.

**Comment by avluis** [comment]
> I actually found the issue in the latest master as well.I actually found the issue in the latest master as well.

Are you purposely ignoring what I'm referring to?
Can you not see:
`This branch has conflicts that must be resolved`?

**Comment by ameykshirsagar** [comment]
Ohh. I am replying from the mail. I will see the conflict issue from my work station

**Comment by Andrew-Quebe** [comment]
@ameykshirsagar just curious...how come all the commits are by someone else, yet you're making the PR? Is @arcoirislabs your organization?

**Comment by ameykshirsagar** [comment]
Yes @arcoirislabs is my organisation, but my friend was using the account to maintain other repositories and he raised the issue.

**Comment by ameykshirsagar** [comment]
I am not understanding why my changes are creating conflicts

**Comment by Andrew-Quebe** [comment]
@ameykshirsagar it's most likely because you're working off an outdated fork. Perhaps stash your changes and fork the latest version of the lib, and then unstash your changes there.

**Pull request closed without merging**
