### PR TITLE
Update project dependencies

### PR DESCRIPTION
**Pull request by friederbluemle**
This updates all project dependencies to the latest versions.

### CODE REVIEW

**Comment by avluis** [comment]
Looks good from my end -- and the updated dependency to API 24 is good, but please try to keep actual fixes separate from dependency updates on future PRs.

**Comment by friederbluemle** [comment]
> please try to keep actual fixes separate from dependency updates on future PRs.

Sure! I removed the fix commit, and will submit another PR once this one is merged. Thanks.

**Comment by friederbluemle** [comment]
@avluis Any other comments? Can this be merged? Thanks.

**Comment by avluis** [comment]
Waiting for @PaoloRotolo or @Andrew-Quebe to merge as I haven't heard from them in a bit as to what they would be happy with.

**Comment by PaoloRotolo** [comment]
OK for me, thanks.

**Pull request merged**
