### PR TITLE
Support for long descriptions

### PR DESCRIPTION
**Pull request by SandroMachado**
This PR improves the base fragment intro layout to add support for longer descriptions.

Before:
screenshot_20160528-000253

After:
*HDPI*
screenshot_20160528-000331

*XXHDPI*
baconmmb29xsandromachado05282016000617

### CODE REVIEW

**Comment by SandroMachado** [comment]
@avluis thanks for the feedback!

Please let me know WDYT of the new approach.

**Comment by avluis** [comment]
This is with your changes, about how many line do you feel are sufficient? :smiley: 

device-2016-06-02-205505

IMO, if the developer needs any more than is provided by this, then they should be creating their own layout, right?

**Comment by SandroMachado** [comment]
Yup :)

**Comment by SandroMachado** [comment]
@avluis same question again. =)
There is any ETA for the next release or there is an ETA to merge this into master to I be able to use `JitPack`?

Thanks

**Comment by avluis** [comment]
Unfortunately I have not heard anything from @PaoloRotolo or @Andrew-Quebe lately, they must be busy.
I can only try and make it a bit easier for them once they have some free time, but I won't be merging changes in unless I hear it is OK to do so from either of them.

**Comment by SandroMachado** [comment]
@avluis Thanks for the reply!

**Comment by PaoloRotolo** [comment]
Looks good to me, thanks.

**Pull request merged**
