### PR TITLE
Add Back-Button-Navigation

### PR DESCRIPTION
**Pull request by beatbrot**
Added support to navigate to previous slide with the back button, as requested [here](https://github.com/paolorotolo/AppIntro/issues/352).

### CODE REVIEW

**Comment by avluis** [comment]
I don't mean to pick, specially since the code was provided for free and out of someone else's time - but can we get a bit of code consistency going on for the whole project;
@Andrew-Quebe I think we need to write down some code style rules for this repo don't we? 🏃

**Comment by Andrew-Quebe** [comment]
@avluis what do you mean? I reviewed the code and it seemed fine.

**Comment by beatbrot** [comment]
@avluis I'll take another look at the code later again :) I'll definitely add the necessary braces and hopefully find more stuff to clean up :)

**Comment by avluis** [comment]
@Andrew-Quebe Yes -- the code is fine, is just a consistency issue which @beatbrot is already on top off. 🐈

**Pull request merged**
