### PR TITLE
Set visibility of Skip button

### PR DESCRIPTION
**Pull request by RafaG**
If you want old style AppIntro2 without Skip button, you can set setSkipButtonEnabled(false).

### CODE REVIEW

**Comment by RafaG** [comment]
Missing setter.

**Comment by avluis** [comment]
Why not move the method in AppIntro to AppIntroBase so that they are shared across AppIntro and AppIntro2?

**Comment by RafaG** [comment]
I think that functionality of Skip button is well controlled by skipButtonEnabled in AppIntroBase and we have a method to see the status, but not to changed it.

You need to change skipButtonEnabled to false in order to work correclty setProgressButtonEnabled().

**Comment by avluis** [comment]
I don't think you understand what I meant - I'm not talking about why adding a way to disable the skip button in AppIntro2 - that is fine; I am talking about adding an additional method to the library, which is what this PR does.

If you move the following from AppIntro into AppIntroBase, would this not do the same as this PR?
```java
public void showSkipButton(boolean showButton) {
    this.skipButtonEnabled = showButton;
    setButtonState(skipButton, showButton);
}
```

**Comment by RafaG** [comment]
Ok, now I understand you, I was working only with AppIntro2 and don't saw this method .For sure is better what you think.

**Comment by avluis** [comment]
Awesome, if you update the PR with what I have commented above AND remove that same code from AppIntro, I will bring it up with @Andrew-Quebe to see if he agrees on the merge.

**Comment by avluis** [comment]
Better, but that same method has to be removed from AppIntro as well, go ahead and get that change in there as well.
Should be from [here](https://github.com/PaoloRotolo/AppIntro/blob/master/library/src/main/java/com/github/paolorotolo/appintro/AppIntro.java#L102) to [there](https://github.com/PaoloRotolo/AppIntro/blob/master/library/src/main/java/com/github/paolorotolo/appintro/AppIntro.java#L111).

**Comment by avluis** [comment]
Awesome, thanks again~

**Comment by RafaG** [comment]
Thanks a lot. I never worked with git before and I was not so sure what I was doing. :-)

**Comment by avluis** [comment]
@PaoloRotolo or @Andrew-Quebe Do you mind taking a look at this PR and merge if it satisfies you? :eyes:

**Comment by PaoloRotolo** [comment]
Sure, looks good to me. Sorry for the delay.

**Pull request merged**
