### PR TITLE
[WIP] Refactoring, bugfixes add slide policy

### PR DESCRIPTION
**Pull request by maxee**
As the maintainers seem quite inactive for a few month now, I decided to create a PR which addresses a lot of issues and implements a few new features, I'd like to have.

@PaoloRotolo and @Andrew-Quebe: If you don't want to merge the whole PR but only parts, let me know, for most points I mention in the following list, it would be possible to create a own PR, if requested.

**Note:** All changes are backward compatible and don't break any implementation.

- [x] ~~Go back to stable version of the gradle plugin to prevent warnings when using an outdated preview version (45e7a1a)~~ Edit: Plugin version changed to v2.0.0 stable (768680e)
- [x] Add missing import (576392e). Same as #199 and #207 
- [x] The classes `AppIntro` and `AppIntro2` share a lot of common code. This is ugly, a common parent class would solve it (7c4008b and c0b2d53)
- [x] The function `onNextPressed` is useless. (Marked as deprecated in 55c7034)
- [x] #134, #175 : Add new functions with changed signature of `onSlideChanged`, `onDonePressed` and `onSkipPressed` returning the instance of the current fragment, mark the old ones as deprecated. (55c7034)
- [x] #129: Add the possibility to have some fragment-based policy on whether ~~going to the next slide, pressing done, pressing skip (#100)~~ leaving the intro by pressing the back button is enabled. E.g.: One has a fragment with a license text which should be acknowledged by ticking a checkbox. The fragment should be able to lock the intro until the user checked the checkbox. (Method `setGoBackLock` implemented d014eed)
- [x] #119: Let users override `onCreate()`, mark `init()` as deprecated (2941c7f)
- [x] remove custom method `restoreLockingState` and override `onRestoreInstanceState` instead (2941c7f).
- [x] Consolidate layout files `layout_intro.xml` and `layout_intro2.xml`. Both have a almost completly indentical file for the layout-v21 stuff. This could be easier done via a small style. Also as mentioned in #142, both contain unnecessary color declarations (2153055 and b9b36c9)
- [x] Implement support for immersive mode. Add two methods `setImmersiveMode(isEnabled)` and `setImmersiveMode(isEnabled, isSticky)`. The former is a shorthand method for the latter with the second parameter set to false. (c8e7825)
- [ ] Implement correct fragment instance saving and restoring (for example on orientation changes). 
  - 94c480e: Implemented basic support for saving and restoring supported fragments. Custom fragments need to override `onSaveInstanceState` and restore data manually. `AppIntroFragment` supports this behavior natively now.
- [x] Implement callbacks to slides if they were selected or deselected. Custom fragements may implement `ISlideSelectionListener` which contains the two methods `onSlideSelected` and `onSlideDeselected`. These methods will be called automatically. Extend AppIntroFragment to implement `ISlideSelectionListener`. (0f529ee)
- [x] Split `AppIntroFragment` into` AppIntroFragment` and `AppIntro2Fragment` with a common super class in order to be able to set the different bottom paddings of the two layouts accordingly (Layout: 64dp, Layout2: 80dp). Add `fragment_intro.xml` and `fragment_intro2.xml` with common layout xml `fragment_intro_content.xml`. (cf81e46).
- [x] Add some default styles and dimensions for easier cusomisation (i.e. custom slides) (ef87b30
):
 1. Style `AppIntroDefaultPadding` adds some basic padding to the slide, respecting the status bar's height. This style does not respect the bottom bars height, if the content is too high, it will underlay the bottom bar.
 2. Style `AppIntroDefaultPadding.Intro1`: Same as i) but with additional padding at the bottom to respect the bottom bar's height (normal layout)
 3. Style `AppIntroDefaultPadding.Intro2`: Same as i) but with additional padding at the bottom to respect the bottom bar's height (Layout2)
 4. Style `AppIntroDefaultHeading`: Default style for a slide's heading
 5. Style `AppIntroDefaultText`: Default style for a slide's text
- [x] #186: Add support for color transitions. Color transitions are only available if all slides implement `ISlideBackgroundColorHolder` and can be enabled and disabled via `setColorTransitionsEnabled(boolean)`. `AppIntroFragment` and `AppIntroFragment2` implement this interface by default. (c963ce4 and 11d5e23)

### CODE REVIEW

**Comment by danluong** [comment]
Regarding the last item with enabling/disabling fragments, this functionality is already included, please see #100, although it hasn't been added to the readme/instructions and probably should be.

**Comment by maxee** [comment]
@danluong: Aaah, thanks didn't get that one, but there is stilling a missing lock that prevents leaving the intro by pressing the back button.

**Comment by PaoloRotolo** [comment]
Wow, it seems good to me. @Andrew-Quebe what do you think?

**Comment by maxee** [comment]
I added a slide with some input elements to the example app's `DefaultIntro` in order to demonstrate fragment retaining.
However, I didn't overhaul the example app and readme yet. 

Another feature I'll implement is some callback functionality slide -> activity to be able to lock the intro directly without `((AppIntro)getActivity)....`.

**Comment by PaoloRotolo** [comment]
So, wow. Thanks for your work. I'll release a new version on Maven soon.

**Comment by maxee** [comment]
Thanks for merging, however I might add some further changes regarding slide-based locking in the next days. Also the readme isn't up to date anymore.

I will create a new PR for further changes.

**Comment by Andrew-Quebe** [comment]
@maxee some awesome work man! Very detailed PR...one of the best I've ever seen in my open source experience!

**Comment by maxee** [comment]
@Andrew-Quebe, thanks and you're welcome, I hope, everything works as expected, for me all tests worked. Maybe you could test it a bit before releasing a new version in order to be sure, but most of the changes are refactoring-related :)

I hope I'll find time to update the readme file within the next days.

Also the example app does not demonstrate the new color transition, lock and immersive mode capabilities at this time.

**Comment by Andrew-Quebe** [comment]
@maxee I'll look into updating the Readme as well as the sample once we release on Maven.

**Pull request merged**
