### PR TITLE
Added Previous button + Made xamarin binding easy

### PR DESCRIPTION
**Pull request by YoupHulsebos**
Added the previous button and made some public/private changes to make xamarin.android binding work out of the box.

### CODE REVIEW

**Comment by avluis** [comment]
When was this requested?
Could you link to the issue #?

Also, when modifying AppIntro, the example app needs to be updated to showcase the change the PR makes, along with demonstrating that it does not break existing features.

**Comment by YoupHulsebos** [comment]
I didn't request the features. But I needed the back button in our own AppIntro. So since I added it, I thought I would share. Ill update the example app to showcase the change and make sure to demonstrate that it does not break existing features.

**Comment by ameykshirsagar** [comment]
@YoupHulsebos : The back button in navigation feature is a part of larger motive to create a wizard page where you need to add such navigation as per your requirements, and it is being addressed in [267](https://github.com/PaoloRotolo/AppIntro/pull/267). Kindly check it out to confirm that is it what you were trying to do.

**Comment by avluis** [comment]
OK, so I'm seeing a bit of conflict with this PR and #267 -- at this point, I just need to know what does this PR address that PR #267 does not?

**Comment by ameykshirsagar** [comment]
@avluis : Probably the xamarin binding is what [#267](https://github.com/PaoloRotolo/AppIntro/pull/267) is not addressing.

**Comment by avluis** [comment]
Understandable -- but changes will need to be taken into consideration with this PR when #267 is merged.
If Xamarin binding is still desired, then please update this PR when #267 is merged.

**Comment by avluis** [comment]
Marking this as abandoned.

**Pull request closed without merging**
