### PR TITLE
Use CharSequence instead of String

### PR DESCRIPTION
**Pull request by tasomaniac**
With the usage of `CharSequence` object, the users of the library can send `SpannableString` to adjust the styles of the texts.

### CODE REVIEW

**Comment by Andrew-Quebe** [comment]
#138 is causing conflicts with this PR...please make a new one that keeps the Spannable text feature. Thank you :)

**Comment by tasomaniac** [comment]
I was going to do that but it is almost impossible with #138 merged. I would suggest you to revert that merge. 

It is using `Html.fromHtml` first. And then in `newInstance` method, it uses `Html.toHtml` to revert it and then uses `Html.fromHtml` one more time in `onCreateView`. That is bad for performance and does not make sense. 

Besides, `Html.fromHtml` is not the only way to use Spans.

**Comment by Andrew-Quebe** [comment]
Perhaps you could include a more performance friendly way of using spans?

**Comment by tasomaniac** [comment]
I already sent a PR about it. Can you check #143

**Pull request closed without merging**
