### PR TITLE
Add description spannable support

### PR DESCRIPTION
**Pull request by SandroMachado**
This PR adds support to add a slide description with a spannable string.

baconlmy48bsandromachado12312015005934

### CODE REVIEW

**Comment by Andrew-Quebe** [comment]
Git is being very strange and claiming merge conflicts. I've copied your code and pushed it through on the master branch manually. If it doesn't work, make a new PR and I'll merge it.

**Comment by SandroMachado** [comment]
Thanks Andrew! Any plans to a release with this change? It will be very helpful :)

**Comment by Andrew-Quebe** [comment]
@SandroMachado not yet. I'm not in charge of pushing the library to maven. @PaoloRotolo probably knows when the next release is. 

However, there are several issues that are being worked on before a release. Your work will be one of many things changed for the next version.

**Comment by SandroMachado** [comment]
@Andrew-Quebe thanks for the reply... Looking forward to the next release!

**Pull request closed without merging**
