### PR TITLE
Added animation to views

### PR DESCRIPTION
**Pull request by Sumeet21**
Added transformPage interface to fragments so any one can animate view property

### CODE REVIEW

**Comment by Sumeet21** [comment]
want to implement intro pages like this [https://medium.com/@BashaChris/the-android-viewpager-has-become-a-fairly-popular-component-among-android-apps-its-simple-6bca403b16d4#.e7q1adysy](url) so created interface myself

**Comment by Andrew-Quebe** [comment]
Can you push some changes to the example app so I can get a feel for what you've implemented?

**Comment by Sumeet21** [comment]
updated sample app 
DefaultIntro

**Comment by avluis** [comment]
Can you update this PR to account for changes in master.

**Comment by Andrew-Quebe** [comment]
Last update was June 2 and was a request to update this PR to match the current branch. @Sumeet21 if you want this merged, update your PR and reopen this one.

**Pull request closed without merging**
