### PR TITLE
Add indonesia string

### PR DESCRIPTION
**Pull request by mychaelgo**

### CODE REVIEW

**Comment by Andrew-Quebe** [comment]
Thanks a lot!

**Comment by Andrew-Quebe** [comment]
@mychaelgo refer to issue #5 again if you want to help translate the example app strings.

**Comment by mychaelgo** [comment]
@Andrew-Quebe noted 👍

**Comment by Andrew-Quebe** [comment]
Just keep in mind that the sample app isn't done, and more strings will be added as time goes on.

**Pull request merged**
